zuul:
  routes:
    user:
      path: /api/login/**
      url: http://localhost:8082/login
    user2:
      path: /api/registration/**
      url: http://localhost:8082/registration
    todos:
      path: /api/todos/**
      url: http://localhost:8080/todos

server:
  port: 8088