server:
  port: 8088
  context-path: /api

zuul:
  routes:
    user:
      path: /users/**
      url: http://localhost:8082
      stripPrefix: false

    todos:
      path: /todos/**
      url: http://localhost:8080
      stripPrefix: false

    tags:
      path: /tags/**
      serviceId: http://localhost:8080
      stripPrefix: false
